platform :ios, '8.0'
inhibit_all_warnings!

target "banmen" do
 use_frameworks!
 pod "AFNetworking", "~> 3.0"
 pod 'SDWebImage', '~> 3.8'
 pod 'MJRefresh'
 pod 'Masonry'
 pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'
 pod 'MJExtension'
 pod 'TYAlertController'
 pod 'JKDBModel-JDBR', '~> 0.0.1'
 pod 'Charts'
 # 集成微信(精简版0.2M)
 pod ‘UMengUShare/Social/ReducedWeChat'
 # 集成QQ/QZone/TIM(精简版0.5M)
 pod ‘UMengUShare/Social/ReducedQQ'
 # 集成新浪微博(精简版1M)
 pod ‘UMengUShare/Social/ReducedSina'
 # U-Share SDK UI模块（分享面板，建议添加）
 pod ‘UMengUShare/UI’
 pod 'JPush', '3.0.2'
end
